version: '3'
services:
  t2bserver:
    image: time2backup/server
    build: .
    ports:
      - '9922:22'
    volumes:
      - ./backups:/backups
      - ./config:/config:ro
    restart: unless-stopped
